var mongoose = require('mongoose');
var Schema = mongoose.Schema();
module.exports = {
    user = new Schema({
        _id: {type:string, required:true, unique:true},
        name: {type:string, required:true},
        email: {type:string, required:true, lowercase:true},
        gender: {type:string, enum:["m","f"], default:"f"},
        access_token: {type:string, required:true, unique:true},
        refresh_token: {type:string, required:true, unique:true},
        city : {type:string, default:""},
        news_letter: {type:boolean, default:false},
        status : {type:boolean, default:false},
        last_location: {type:string, default:""},
        joining_date: {type:number, required},
        last_active: {type:number, require},
        auth_type: {type:string, enum:["faagio","google","facebook"]},
        password: {type:string, default:""},
        profile_status: {type:boolean, default:true},
        social_id :{type:number, default:0},
        phone: [string]
    }),
    outletGallery = new Schema({
        image_id: {type:string, required:true},
        image: {type:string, required:true} 
    }),
    outletTiming = new Schema({
        sunday: {type:string, required:true},
        monday: {type:string, required:true},
        tuesday: {type:string, required:true},
        wednesday: {type:string, required:true},
        thursday: {type:string, required:true},
        friday: {type:string, required:true},
        saturday: {type:string, required:true}
    }),
    outlet = new Schema({
        _id: {type:string, required:true, unique:true},
        email: {type:string, required:true, unique:true},
        password: {type:string, required:true},
        name: {type:string, required:true},
        address: {type:string, required:true},
        locality: {type:string, required:true},
        zones: {type:string, required:true},
        region: {type:string, required:true},
        near_by: {type:string, required:true},
        page_url: {type:string, required:true},
        cost_rate: {type:number, required:true},
        cover_image: {type:string, required:true},
        outlet_owner: {type:string, required:true},
        outlet_time: {type:string},
        website: {type:string, required:true},
        phone_no: {type:string, required:true},
        video: {type:string, required:true},
        did_you_know: {type:string, required:true},
        parking: {type:string, required:true},
        authorised_dealer: {type:string, required:true},
        brand_desc: {type:string, required:true},
        brands: {type:string, required:true},
        category: {type:string, required:true},
        user_name: {type:string, required:true},
        latitude: {type:number, required:true},
        longitude: {type:number, required:true},
        gallery: [outletGallery],
        rating: {type:string, required:true},
        voters: {type:string, required:true},
        contacts: [string],
        outlet_type: [{type:string, required:true}],
        timing: outletTiming,
        outlet_accept: [string],
        description: {type:string, required:true},
        tags: [string],
        gender: [string],
        exchange: [string],
        labels: [string],
    }),
    review = new Schema({
        _id: {type:string, required:true, unique:true},
        review: {type:string, required:true},
        images: [string],
        comments: [string],
        likes: [string],
        date: {type:number,required:true}
    }),
    rating = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        star: number,
        reviews: [review],
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        date: {type:number, required:true},
    }),
    bookMark = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        date: {type:number, required:true},
    }),
    checkIn = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        public: {type:boolean, required:true, default:true},
        date: {type:number, required:true},
    }),
    images = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        image: {type:string, required:true},
        uploaded_by: {type:string, required:true, enum:["admin","outlet","user"]},
    }),
    reviewComments = new Schema({
        _id: {type:string, required:true, unique:true},
        review_id: {type:string, required:true},
        user_id: {type:string, required:true},
        comment: {type:string, required:true},
        date: {type:number, required:true},
    }),
    reviewLikes = new Schema({
        _id: {type:string, required:true, unique:true},
        review_id: {type:string, required:true},
        user_id: {type:string, required:true},
        like_dislike: {type:boolean, required:true, default:true},
        date: {type:number, required:true},
    }),
    imageComments = new Schema({
        _id: {type:string, required:true, unique:true},
        image_id: {type:string, required:true},
        user_id: {type:string, required:true},
        comment: {type:string, required:true},
        image_type: {type:string, required:true},
        date: {type:number, required:true},
    }),
    imageLikes = new Schema({
        _id: {type:string, required:true, unique:true},
        image_id: {type:string, required:true},
        user_id: {type:string, required:true},
        image_type: {type:string, required:true},
        date: {type:number, required:true},
    }),
    errorReport = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        header: {type:boolean, required:true, default:false},
        about: {type:boolean, required:true, default:false},
        stm: {type:boolean, required:true, default:false},
        timing: {type:boolean, required:true, default:false},
        labels: {type:boolean, required:true, default:false},
        reviews: {type:boolean, required:true, default:false},
        tags: {type:boolean, required:true, default:false},
        date: {type:number, required:true}
    }),
    shutdownReport = new Schema({
        _id: {type:string, required:true, unique:true},
        outlet_id: {type:string, required:true},
        user_id: {type:string, required:true},
        category: {type:string, required:true, enum:["book","cloth","consumer","watch"]},
        date: {type:number, required:true}        
    })
}